models:
  - name: googlenet-v4
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/googlenet-v4/FP32/googlenet-v4.xml
        weights: public/googlenet-v4/FP32/googlenet-v4.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/googlenet-v4/FP16/googlenet-v4.xml
        weights: public/googlenet-v4/FP16/googlenet-v4.bin
        adapter: classification

    datasets:
      - name: imagenet_1001_classes
        preprocessing:
          - type: crop
            central_fraction: 0.875
          - type: resize
            size: 299

global_definitions: ../dataset_definitions.yml
