models:
  - name: i3d-rgb
    launchers:
     - framework: dlsdk
       tags:
         - FP32
       model: public/i3d-rgb/FP32/i3d-rgb.xml
       weights: public/i3d-rgb/FP32/i3d-rgb.bin
       adapter: classification
       inputs:
         - name: Placeholder
           type: INPUT
           layout: NCDHW

     - framework: dlsdk
       tags:
         - FP16
       model: public/i3d-rgb/FP16/i3d-rgb.xml
       weights: public/i3d-rgb/FP16/i3d-rgb.bin
       adapter: classification
       inputs:
         - name: Placeholder
           type: INPUT
           layout: NCDHW

    datasets:
      - name: kinetics-400-frames-79-400

        reader: pillow_imread
        preprocessing:
        - type: resize
          size: 256
          aspect_ratio_scale: fit_to_window
        - type: crop
          size: 224
        metrics:
          - type: clip_accuracy
            presenter: print_vector
          - name: accuracy@top1
            type: accuracy
            top_k: 1
          - name: accuracy@top5
            type: accuracy
            top_k: 5

global_definitions: ../datasets_definitions.yml
