models:
  - name: MobileNet-v3-large-pytorch
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model: mobilenet-v3-large/caffe2/FP32/mobilenet-v3-large.xml
        weights: mobilenet-v3-large/caffe2/FP32/mobilenet-v3-large.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model: mobilenet-v3-large/caffe2/FP16/mobilenet-v3-large.xml
        weights: mobilenet-v3-large/caffe2/FP16/mobilenet-v3-large.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - INT8
        model: mobilenet-v3-large/caffe2/INT8/mobilenet-v3-large.xml
        weights: mobilenet-v3-large/caffe2/INT8/mobilenet-v3-large.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP32-INT8
        model: mobilenet-v3-large/caffe2/FP32-INT8/mobilenet-v3-large.xml
        weights: mobilenet-v3-large/caffe2/FP32-INT8/mobilenet-v3-large.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16-INT8
        model: mobilenet-v3-large/caffe2/FP16-INT8/mobilenet-v3-large.xml
        weights: mobilenet-v3-large/caffe2/FP16-INT8/mobilenet-v3-large.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
        - type: resize
          size: 256
          aspect_ratio_scale: greater
          use_pillow: true
          interpolation: BILINEAR
        - type: crop
          use_pillow: true
          size: 224

        metrics:
          - name: accuracy @ top1
            type: accuracy
            top_k: 1

          - name: accuracy @ top5
            type: accuracy
            top_k: 5
