models:
  - name: retinaface-mobilenetv2-0.25-modified
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   retinaface-mobilenetv2-0.25-modified/caffe/FP32/retinaface-mobilenetv2-0.25-modified.xml
        weights: retinaface-mobilenetv2-0.25-modified/caffe/FP32/retinaface-mobilenetv2-0.25-modified.bin
        adapter:
          type: retinaface
          bboxes_outputs:
            - face_rpn_bbox_pred_stride32
            - face_rpn_bbox_pred_stride16
            - face_rpn_bbox_pred_stride8
          scores_outputs:
            - face_rpn_cls_prob_reshape_stride32
            - face_rpn_cls_prob_reshape_stride16
            - face_rpn_cls_prob_reshape_stride8
      - framework: dlsdk
        tags:
          - FP16
        model:   rretinaface-mobilenetv2-0.25-modified/caffe/FP16/retinaface-mobilenetv2-0.25-modified.xml
        weights: retinaface-mobilenetv2-0.25-modified/caffe/FP16/retinaface-mobilenetv2-0.25-modified.bin
        adapter:
          type: retinaface
          bboxes_outputs:
            - face_rpn_bbox_pred_stride32
            - face_rpn_bbox_pred_stride16
            - face_rpn_bbox_pred_stride8
          scores_outputs:
            - face_rpn_cls_prob_reshape_stride32
            - face_rpn_cls_prob_reshape_stride16
            - face_rpn_cls_prob_reshape_stride8
      - framework: dlsdk
        tags:
          - FP32-INT8
        model:   retinaface-mobilenetv2-0.25-modified/caffe/FP32-INT8/retinaface-mobilenetv2-0.25-modified.xml
        weights: retinaface-mobilenetv2-0.25-modified/caffe/FP32-INT8/retinaface-mobilenetv2-0.25-modified.bin
        adapter:
          type: retinaface
          bboxes_outputs:
            - face_rpn_bbox_pred_stride32
            - face_rpn_bbox_pred_stride16
            - face_rpn_bbox_pred_stride8
          scores_outputs:
            - face_rpn_cls_prob_reshape_stride32
            - face_rpn_cls_prob_reshape_stride16
            - face_rpn_cls_prob_reshape_stride8
      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   retinaface-mobilenetv2-0.25-modified/caffe/FP16-INT8/retinaface-mobilenetv2-0.25-modified.xml
        weights: retinaface-mobilenetv2-0.25-modified/caffe/FP16-INT8/retinaface-mobilenetv2-0.25-modified.bin
        adapter:
          type: retinaface
          bboxes_outputs:
            - face_rpn_bbox_pred_stride32
            - face_rpn_bbox_pred_stride16
            - face_rpn_bbox_pred_stride8
          scores_outputs:
            - face_rpn_cls_prob_reshape_stride32
            - face_rpn_cls_prob_reshape_stride16
            - face_rpn_cls_prob_reshape_stride8
    datasets:
      - name: wider
        preprocessing:
          - type: resize
            size: 640
        postprocessing:
          - type: cast_to_int
          - type: clip_boxes
            size: 1024
            apply_to: annotation
          - type: filter
            apply_to: annotation
            height_range: 64, 1024
            is_empty: True

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: False
            distinct_conf: False

global_definitions: ../dataset_definitions.yml
