models:
  - name:  ssd_mobilenet_v2
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   ssd_mobilenet_v2/tf/FP32/ssd_mobilenet_v2.xml
        weights: ssd_mobilenet_v2/tf/FP32/ssd_mobilenet_v2.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16
        model:   ssd_mobilenet_v2/tf/FP16/ssd_mobilenet_v2.xml
        weights: ssd_mobilenet_v2/tf/FP16/ssd_mobilenet_v2.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP32-INT8
        model:   ssd_mobilenet_v2/tf/FP32-INT8/ssd_mobilenet_v2.xml
        weights: ssd_mobilenet_v2/tf/FP32-INT8/ssd_mobilenet_v2.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   ssd_mobilenet_v2/tf/FP16-INT8/ssd_mobilenet_v2.xml
        weights: ssd_mobilenet_v2/tf/FP16-INT8/ssd_mobilenet_v2.bin
        adapter: ssd

    datasets:
      - name: ms_coco_detection_91_classes
        preprocessing:
          - type: resize
            dst_width: 256
            dst_height: 256
        postprocessing:
          - type: resize_prediction_boxes
        metrics:
          - type: coco_precision

global_definitions: ../dataset_definitions.yml
