models:
  - name:  ssd_mobilenet_v2_quantized
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   ssd_mobilenet_v2_quantized/tf/FP32/ssd_mobilenet_v2_quantized.xml
        weights: ssd_mobilenet_v2_quantized/tf/FP32/ssd_mobilenet_v2_quantized.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16
        model:   ssd_mobilenet_v2_quantized/tf/FP16/ssd_mobilenet_v2_quantized.xml
        weights: ssd_mobilenet_v2_quantized/tf/FP16/ssd_mobilenet_v2_quantized.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP32-INT8
        model:   ssd_mobilenet_v2_quantized/tf/FP32-INT8/ssd_mobilenet_v2_quantized.xml
        weights: ssd_mobilenet_v2_quantized/tf/FP32-INT8/ssd_mobilenet_v2_quantized.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   ssd_mobilenet_v2_quantized/tf/FP16-INT8/ssd_mobilenet_v2_quantized.xml
        weights: ssd_mobilenet_v2_quantized/tf/FP16-INT8/ssd_mobilenet_v2_quantized.bin
        adapter: ssd

    datasets:
      - name: ms_coco_detection_91_classes

        preprocessing:
          - type: resize
            size: 300
        postprocessing:
          - type: resize_prediction_boxes
        metrics:
          - type: coco_precision
            max_detections: 100

global_definitions: ../dataset_definitions.yml
