models:
  - name:  ssdlite_mobilenet_edgetpu_coco_quant
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   ssdlite_mobilenet_edgetpu_coco_quant/tf/FP32/ssdlite_mobilenet_edgetpu_coco_quant.xml
        weights: ssdlite_mobilenet_edgetpu_coco_quant/tf/FP32/ssdlite_mobilenet_edgetpu_coco_quant.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16
        model:   ssdlite_mobilenet_edgetpu_coco_quant/tf/FP16/ssdlite_mobilenet_edgetpu_coco_quant.xml
        weights: ssdlite_mobilenet_edgetpu_coco_quant/tf/FP16/ssdlite_mobilenet_edgetpu_coco_quant.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP32-INT8
        model:   ssdlite_mobilenet_edgetpu_coco_quant/tf/FP32-INT8/ssdlite_mobilenet_edgetpu_coco_quant.xml
        weights: ssdlite_mobilenet_edgetpu_coco_quant/tf/FP32-INT8/ssdlite_mobilenet_edgetpu_coco_quant.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   ssdlite_mobilenet_edgetpu_coco_quant/tf/FP16-INT8/ssdlite_mobilenet_edgetpu_coco_quant.xml
        weights: ssdlite_mobilenet_edgetpu_coco_quant/tf/FP16-INT8/ssdlite_mobilenet_edgetpu_coco_quant.bin
        adapter: ssd

    datasets:
      - name: ms_coco_detection_91_classes

        preprocessing:
          - type: resize
            size: 320
        postprocessing:
          - type: resize_prediction_boxes
        metrics:
          - type: coco_precision
            max_detections: 100

global_definitions: ../dataset_definitions.yml
